/********************************************************************************
** Form generated from reading ui file 'gui.ui'
**
** Created: Thu Oct 4 21:50:55 2007
**      by: Qt User Interface Compiler version 4.3.1
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_GUI_H
#define UI_GUI_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QLabel>
#include <QtGui/QProgressBar>
#include <QtGui/QPushButton>
#include <QtGui/QSlider>
#include <QtGui/QSpinBox>
#include <QtGui/QTextEdit>
#include <QtGui/QWidget>
#include "qwt_plot.h"

class Ui_Gui
{
public:
    QPushButton *btnExit;
    QPushButton *btnReset;
    QGroupBox *groupBoxNetwork;
    QTextEdit *textEditNetworkLog;
    QPushButton *btnSaveNetworkLog;
    QPushButton *btnClearNetworkLog;
    QGroupBox *groupBoxLog;
    QPushButton *btnClearLog;
    QPushButton *btnSaveLog;
    QTextEdit *textEditLog;
    QPushButton *btnTest;
    QPushButton *btnEnableRemote;
    QPushButton *btnDrive;
    QGroupBox *groupBoxLaserScanner;
    QCheckBox *checkBoxAngleView;
    QSlider *sliderLaserScale;
    QCheckBox *checkBoxHiResView;
    QLabel *labelLaserTop;
    QLabel *label_10;
    QLabel *label_11;
    QFrame *lineLaser90;
    QFrame *lineLaser0;
    QCheckBox *checkBoxLaserAlert;
    QCheckBox *checkBoxAntiAlias;
    QGroupBox *groupBoxSettings;
    QSpinBox *spinBoxMotor1Speed;
    QSlider *sliderMotor1Speed;
    QSpinBox *spinBoxBotSlot;
    QSpinBox *spinBoxPositionServo1;
    QSlider *sliderBotSlot;
    QSlider *sliderMotor2Speed;
    QLabel *label;
    QCheckBox *checkBoxSaveSettings;
    QLabel *label_5;
    QSlider *sliderPositionServo1;
    QSpinBox *spinBoxObstacle;
    QSlider *sliderObstacle;
    QLabel *label_4;
    QLabel *label_3;
    QLabel *label_2;
    QSpinBox *spinBoxMotor2Speed;
    QSpinBox *spinBoxObstacleLaserScanner;
    QSlider *sliderObstacleLaserScanner;
    QLabel *label_9;
    QGroupBox *groupBoxMotor;
    QwtPlot *qwtPlotCurrent1;
    QLabel *textLabel2_6;
    QLabel *textLabel2_7;
    QPushButton *btnResetMovement1;
    QLabel *labelDrivenDistance1;
    QLabel *labelDrivenDistance2;
    QLabel *textLabel1_2;
    QFrame *frameDirection2;
    QLabel *lblDirection2;
    QPushButton *btnResetMovement2;
    QFrame *frameDirection1;
    QLabel *lblDirection1;
    QLabel *textLabel1;
    QFrame *framePower1;
    QLabel *lblPower1;
    QwtPlot *qwtPlotCurrent2;
    QFrame *framePower2;
    QLabel *lblPower2;
    QLabel *labelRevolutions2;
    QLabel *labelRevolutions1;
    QGroupBox *groupBoxCamera;
    QPushButton *btnClearPicture;
    QPushButton *btnAutoSavePicture;
    QCheckBox *checkBoxCamPicLive;
    QPushButton *btnSavePicture;
    QCheckBox *checkBoxAutoSave;
    QGroupBox *groupBoxBot;
    QLabel *labelSensorAlarm1;
    QLabel *label_7;
    QLabel *labelSensorAlarm4;
    QLabel *labelSensorDistance5;
    QProgressBar *progressBarSensor5;
    QProgressBar *progressBarSensor4;
    QLabel *labelSensorDistance16;
    QLabel *labelSensorAlarm2;
    QLabel *labelSensorAlarm16;
    QLabel *labelSensorAlarm8;
    QLabel *labelSensorAlarm5;
    QLabel *labelSensorAlarm7;
    QLabel *labelSensorDistance4;
    QProgressBar *progressBarSensor7;
    QLabel *lblRobotPic;
    QLabel *labelSensorDistance2;
    QLabel *labelSensorDistance8;
    QProgressBar *progressBarSensor6;
    QProgressBar *progressBarSensor3;
    QLabel *label_6;
    QLabel *labelSensorAlarm3;
    QLabel *labelSensorDistance3;
    QLabel *labelSensorDistance6;
    QLabel *labelSensorDistance7;
    QProgressBar *progressBarSensor2;
    QProgressBar *progressBarSensor8;
    QLabel *labelSensorAlarm6;
    QProgressBar *progressBarSensor16;
    QProgressBar *progressBarSensor1;
    QLabel *labelSensorDistance1;
    QPushButton *btnSimulate;

    void setupUi(QWidget *Gui)
    {
    if (Gui->objectName().isEmpty())
        Gui->setObjectName(QString::fromUtf8("Gui"));
    Gui->resize(1392, 974);
    QSizePolicy sizePolicy(QSizePolicy::Maximum, QSizePolicy::Maximum);
    sizePolicy.setHorizontalStretch(0);
    sizePolicy.setVerticalStretch(0);
    sizePolicy.setHeightForWidth(Gui->sizePolicy().hasHeightForWidth());
    Gui->setSizePolicy(sizePolicy);
    Gui->setWindowIcon(QIcon(QString::fromUtf8(":/images/images/underFootOne.png")));
    Gui->setLayoutDirection(Qt::LeftToRight);
    btnExit = new QPushButton(Gui);
    btnExit->setObjectName(QString::fromUtf8("btnExit"));
    btnExit->setGeometry(QRect(1280, 930, 101, 28));
    btnExit->setIcon(QIcon(QString::fromUtf8(":/images/images/exit.png")));
    btnReset = new QPushButton(Gui);
    btnReset->setObjectName(QString::fromUtf8("btnReset"));
    btnReset->setGeometry(QRect(1280, 670, 101, 28));
    btnReset->setIcon(QIcon(QString::fromUtf8(":/images/images/eraser.png")));
    groupBoxNetwork = new QGroupBox(Gui);
    groupBoxNetwork->setObjectName(QString::fromUtf8("groupBoxNetwork"));
    groupBoxNetwork->setGeometry(QRect(650, 390, 351, 221));
    textEditNetworkLog = new QTextEdit(groupBoxNetwork);
    textEditNetworkLog->setObjectName(QString::fromUtf8("textEditNetworkLog"));
    textEditNetworkLog->setGeometry(QRect(10, 20, 331, 151));
    btnSaveNetworkLog = new QPushButton(groupBoxNetwork);
    btnSaveNetworkLog->setObjectName(QString::fromUtf8("btnSaveNetworkLog"));
    btnSaveNetworkLog->setGeometry(QRect(120, 180, 101, 28));
    btnSaveNetworkLog->setIcon(QIcon(QString::fromUtf8(":/images/images/hdd.png")));
    btnClearNetworkLog = new QPushButton(groupBoxNetwork);
    btnClearNetworkLog->setObjectName(QString::fromUtf8("btnClearNetworkLog"));
    btnClearNetworkLog->setGeometry(QRect(10, 180, 101, 28));
    btnClearNetworkLog->setIcon(QIcon(QString::fromUtf8(":/images/images/trashcan_empty.png")));
    groupBoxLog = new QGroupBox(Gui);
    groupBoxLog->setObjectName(QString::fromUtf8("groupBoxLog"));
    groupBoxLog->setGeometry(QRect(650, 620, 621, 341));
    btnClearLog = new QPushButton(groupBoxLog);
    btnClearLog->setObjectName(QString::fromUtf8("btnClearLog"));
    btnClearLog->setGeometry(QRect(10, 300, 101, 28));
    btnClearLog->setIcon(QIcon(QString::fromUtf8(":/images/images/trashcan_empty.png")));
    btnSaveLog = new QPushButton(groupBoxLog);
    btnSaveLog->setObjectName(QString::fromUtf8("btnSaveLog"));
    btnSaveLog->setGeometry(QRect(120, 300, 101, 28));
    btnSaveLog->setIcon(QIcon(QString::fromUtf8(":/images/images/hdd.png")));
    textEditLog = new QTextEdit(groupBoxLog);
    textEditLog->setObjectName(QString::fromUtf8("textEditLog"));
    textEditLog->setGeometry(QRect(10, 20, 601, 271));
    btnTest = new QPushButton(Gui);
    btnTest->setObjectName(QString::fromUtf8("btnTest"));
    btnTest->setGeometry(QRect(1280, 750, 101, 28));
    btnTest->setIcon(QIcon(QString::fromUtf8(":/images/images/memory.png")));
    btnEnableRemote = new QPushButton(Gui);
    btnEnableRemote->setObjectName(QString::fromUtf8("btnEnableRemote"));
    btnEnableRemote->setGeometry(QRect(1280, 710, 101, 28));
    btnEnableRemote->setIcon(QIcon(QString::fromUtf8(":/images/images/remote.png")));
    btnEnableRemote->setCheckable(true);
    btnDrive = new QPushButton(Gui);
    btnDrive->setObjectName(QString::fromUtf8("btnDrive"));
    btnDrive->setGeometry(QRect(1280, 630, 101, 28));
    btnDrive->setIcon(QIcon(QString::fromUtf8(":/images/images/underFootOne.png")));
    btnDrive->setCheckable(true);
    btnDrive->setDefault(true);
    groupBoxLaserScanner = new QGroupBox(Gui);
    groupBoxLaserScanner->setObjectName(QString::fromUtf8("groupBoxLaserScanner"));
    groupBoxLaserScanner->setGeometry(QRect(10, 0, 621, 301));
    checkBoxAngleView = new QCheckBox(groupBoxLaserScanner);
    checkBoxAngleView->setObjectName(QString::fromUtf8("checkBoxAngleView"));
    checkBoxAngleView->setGeometry(QRect(565, 244, 51, 16));
    checkBoxAngleView->setChecked(true);
    sliderLaserScale = new QSlider(groupBoxLaserScanner);
    sliderLaserScale->setObjectName(QString::fromUtf8("sliderLaserScale"));
    sliderLaserScale->setGeometry(QRect(580, 34, 35, 171));
    sliderLaserScale->setMinimum(1);
    sliderLaserScale->setMaximum(10);
    sliderLaserScale->setPageStep(1);
    sliderLaserScale->setValue(1);
    sliderLaserScale->setSliderPosition(1);
    sliderLaserScale->setTracking(false);
    sliderLaserScale->setOrientation(Qt::Vertical);
    sliderLaserScale->setTickPosition(QSlider::TicksAbove);
    sliderLaserScale->setTickInterval(1);
    checkBoxHiResView = new QCheckBox(groupBoxLaserScanner);
    checkBoxHiResView->setObjectName(QString::fromUtf8("checkBoxHiResView"));
    checkBoxHiResView->setGeometry(QRect(565, 264, 51, 16));
    labelLaserTop = new QLabel(groupBoxLaserScanner);
    labelLaserTop->setObjectName(QString::fromUtf8("labelLaserTop"));
    labelLaserTop->setGeometry(QRect(590, 14, 25, 20));
    label_10 = new QLabel(groupBoxLaserScanner);
    label_10->setObjectName(QString::fromUtf8("label_10"));
    label_10->setGeometry(QRect(560, 190, 21, 20));
    label_11 = new QLabel(groupBoxLaserScanner);
    label_11->setObjectName(QString::fromUtf8("label_11"));
    label_11->setGeometry(QRect(550, 29, 25, 20));
    lineLaser90 = new QFrame(groupBoxLaserScanner);
    lineLaser90->setObjectName(QString::fromUtf8("lineLaser90"));
    lineLaser90->setGeometry(QRect(283, 16, 1, 274));
    QPalette palette;
    QBrush brush(QColor(84, 84, 84, 255));
    brush.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
    palette.setBrush(QPalette::Active, QPalette::Button, brush);
    palette.setBrush(QPalette::Active, QPalette::Light, brush);
    palette.setBrush(QPalette::Active, QPalette::Midlight, brush);
    palette.setBrush(QPalette::Active, QPalette::Dark, brush);
    palette.setBrush(QPalette::Active, QPalette::Mid, brush);
    palette.setBrush(QPalette::Active, QPalette::Text, brush);
    QBrush brush1(QColor(0, 0, 0, 255));
    brush1.setStyle(Qt::SolidPattern);
    palette.setBrush(QPalette::Active, QPalette::BrightText, brush1);
    palette.setBrush(QPalette::Active, QPalette::ButtonText, brush1);
    palette.setBrush(QPalette::Active, QPalette::Base, brush);
    palette.setBrush(QPalette::Active, QPalette::Window, brush);
    palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
    palette.setBrush(QPalette::Active, QPalette::Highlight, brush);
    palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
    palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Light, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Dark, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Mid, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
    palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush1);
    palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush1);
    palette.setBrush(QPalette::Inactive, QPalette::Base, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Window, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
    palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush);
    palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
    palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Light, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Dark, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Mid, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Text, brush);
    palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
    palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Base, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Window, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
    palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush);
    palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
    lineLaser90->setPalette(palette);
    lineLaser90->setAutoFillBackground(true);
    lineLaser90->setFrameShadow(QFrame::Plain);
    lineLaser90->setLineWidth(1);
    lineLaser90->setFrameShape(QFrame::VLine);
    lineLaser0 = new QFrame(groupBoxLaserScanner);
    lineLaser0->setObjectName(QString::fromUtf8("lineLaser0"));
    lineLaser0->setGeometry(QRect(10, 290, 548, 1));
    QPalette palette1;
    palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
    palette1.setBrush(QPalette::Active, QPalette::Button, brush);
    palette1.setBrush(QPalette::Active, QPalette::Light, brush);
    palette1.setBrush(QPalette::Active, QPalette::Midlight, brush);
    palette1.setBrush(QPalette::Active, QPalette::Dark, brush);
    palette1.setBrush(QPalette::Active, QPalette::Mid, brush);
    palette1.setBrush(QPalette::Active, QPalette::Text, brush);
    palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
    palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
    palette1.setBrush(QPalette::Active, QPalette::Base, brush);
    palette1.setBrush(QPalette::Active, QPalette::Window, brush);
    palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Button, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Light, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Base, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::Window, brush);
    palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Button, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Light, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Text, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Base, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::Window, brush);
    palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
    lineLaser0->setPalette(palette1);
    lineLaser0->setAutoFillBackground(true);
    lineLaser0->setFrameShadow(QFrame::Plain);
    lineLaser0->setLineWidth(1);
    checkBoxLaserAlert = new QCheckBox(groupBoxLaserScanner);
    checkBoxLaserAlert->setObjectName(QString::fromUtf8("checkBoxLaserAlert"));
    checkBoxLaserAlert->setGeometry(QRect(565, 224, 51, 16));
    checkBoxLaserAlert->setChecked(true);
    checkBoxAntiAlias = new QCheckBox(groupBoxLaserScanner);
    checkBoxAntiAlias->setObjectName(QString::fromUtf8("checkBoxAntiAlias"));
    checkBoxAntiAlias->setGeometry(QRect(565, 284, 51, 16));
    groupBoxSettings = new QGroupBox(Gui);
    groupBoxSettings->setObjectName(QString::fromUtf8("groupBoxSettings"));
    groupBoxSettings->setGeometry(QRect(1020, 400, 361, 211));
    spinBoxMotor1Speed = new QSpinBox(groupBoxSettings);
    spinBoxMotor1Speed->setObjectName(QString::fromUtf8("spinBoxMotor1Speed"));
    spinBoxMotor1Speed->setGeometry(QRect(10, 10, 46, 23));
    spinBoxMotor1Speed->setMinimum(1);
    spinBoxMotor1Speed->setMaximum(255);
    spinBoxMotor1Speed->setValue(100);
    sliderMotor1Speed = new QSlider(groupBoxSettings);
    sliderMotor1Speed->setObjectName(QString::fromUtf8("sliderMotor1Speed"));
    sliderMotor1Speed->setGeometry(QRect(10, 40, 35, 74));
    sliderMotor1Speed->setMinimum(1);
    sliderMotor1Speed->setMaximum(255);
    sliderMotor1Speed->setValue(100);
    sliderMotor1Speed->setSliderPosition(100);
    sliderMotor1Speed->setOrientation(Qt::Vertical);
    sliderMotor1Speed->setTickPosition(QSlider::TicksBelow);
    sliderMotor1Speed->setTickInterval(20);
    spinBoxBotSlot = new QSpinBox(groupBoxSettings);
    spinBoxBotSlot->setObjectName(QString::fromUtf8("spinBoxBotSlot"));
    spinBoxBotSlot->setGeometry(QRect(250, 10, 46, 23));
    spinBoxBotSlot->setMinimum(1);
    spinBoxBotSlot->setMaximum(180);
    spinBoxBotSlot->setValue(4);
    spinBoxPositionServo1 = new QSpinBox(groupBoxSettings);
    spinBoxPositionServo1->setObjectName(QString::fromUtf8("spinBoxPositionServo1"));
    spinBoxPositionServo1->setGeometry(QRect(310, 10, 46, 23));
    spinBoxPositionServo1->setMinimum(5);
    spinBoxPositionServo1->setMaximum(16);
    spinBoxPositionServo1->setValue(5);
    sliderBotSlot = new QSlider(groupBoxSettings);
    sliderBotSlot->setObjectName(QString::fromUtf8("sliderBotSlot"));
    sliderBotSlot->setGeometry(QRect(250, 40, 35, 74));
    sliderBotSlot->setMinimum(1);
    sliderBotSlot->setMaximum(180);
    sliderBotSlot->setPageStep(2);
    sliderBotSlot->setValue(4);
    sliderBotSlot->setSliderPosition(4);
    sliderBotSlot->setOrientation(Qt::Vertical);
    sliderBotSlot->setTickPosition(QSlider::TicksBelow);
    sliderBotSlot->setTickInterval(18);
    sliderMotor2Speed = new QSlider(groupBoxSettings);
    sliderMotor2Speed->setObjectName(QString::fromUtf8("sliderMotor2Speed"));
    sliderMotor2Speed->setGeometry(QRect(70, 40, 35, 74));
    sliderMotor2Speed->setMinimum(1);
    sliderMotor2Speed->setMaximum(255);
    sliderMotor2Speed->setValue(100);
    sliderMotor2Speed->setSliderPosition(100);
    sliderMotor2Speed->setOrientation(Qt::Vertical);
    sliderMotor2Speed->setTickPosition(QSlider::TicksBelow);
    sliderMotor2Speed->setTickInterval(20);
    label = new QLabel(groupBoxSettings);
    label->setObjectName(QString::fromUtf8("label"));
    label->setGeometry(QRect(130, 120, 52, 31));
    label->setWordWrap(true);
    checkBoxSaveSettings = new QCheckBox(groupBoxSettings);
    checkBoxSaveSettings->setObjectName(QString::fromUtf8("checkBoxSaveSettings"));
    checkBoxSaveSettings->setGeometry(QRect(10, 160, 141, 20));
    label_5 = new QLabel(groupBoxSettings);
    label_5->setObjectName(QString::fromUtf8("label_5"));
    label_5->setGeometry(QRect(70, 120, 41, 31));
    label_5->setWordWrap(true);
    sliderPositionServo1 = new QSlider(groupBoxSettings);
    sliderPositionServo1->setObjectName(QString::fromUtf8("sliderPositionServo1"));
    sliderPositionServo1->setGeometry(QRect(310, 40, 35, 74));
    sliderPositionServo1->setMinimum(5);
    sliderPositionServo1->setMaximum(16);
    sliderPositionServo1->setPageStep(2);
    sliderPositionServo1->setValue(5);
    sliderPositionServo1->setSliderPosition(5);
    sliderPositionServo1->setOrientation(Qt::Vertical);
    sliderPositionServo1->setTickPosition(QSlider::TicksBelow);
    sliderPositionServo1->setTickInterval(1);
    spinBoxObstacle = new QSpinBox(groupBoxSettings);
    spinBoxObstacle->setObjectName(QString::fromUtf8("spinBoxObstacle"));
    spinBoxObstacle->setGeometry(QRect(130, 10, 46, 23));
    spinBoxObstacle->setMinimum(8);
    spinBoxObstacle->setMaximum(47);
    spinBoxObstacle->setSingleStep(1);
    spinBoxObstacle->setValue(47);
    sliderObstacle = new QSlider(groupBoxSettings);
    sliderObstacle->setObjectName(QString::fromUtf8("sliderObstacle"));
    sliderObstacle->setGeometry(QRect(130, 40, 35, 74));
    sliderObstacle->setMinimum(8);
    sliderObstacle->setMaximum(47);
    sliderObstacle->setSingleStep(1);
    sliderObstacle->setPageStep(2);
    sliderObstacle->setValue(47);
    sliderObstacle->setSliderPosition(47);
    sliderObstacle->setOrientation(Qt::Vertical);
    sliderObstacle->setTickPosition(QSlider::TicksBelow);
    sliderObstacle->setTickInterval(3);
    label_4 = new QLabel(groupBoxSettings);
    label_4->setObjectName(QString::fromUtf8("label_4"));
    label_4->setGeometry(QRect(250, 120, 51, 41));
    label_4->setWordWrap(true);
    label_3 = new QLabel(groupBoxSettings);
    label_3->setObjectName(QString::fromUtf8("label_3"));
    label_3->setGeometry(QRect(310, 120, 46, 16));
    label_3->setWordWrap(true);
    label_2 = new QLabel(groupBoxSettings);
    label_2->setObjectName(QString::fromUtf8("label_2"));
    label_2->setGeometry(QRect(10, 120, 41, 31));
    label_2->setWordWrap(true);
    spinBoxMotor2Speed = new QSpinBox(groupBoxSettings);
    spinBoxMotor2Speed->setObjectName(QString::fromUtf8("spinBoxMotor2Speed"));
    spinBoxMotor2Speed->setGeometry(QRect(70, 10, 46, 23));
    spinBoxMotor2Speed->setMinimum(1);
    spinBoxMotor2Speed->setMaximum(255);
    spinBoxMotor2Speed->setValue(100);
    spinBoxObstacleLaserScanner = new QSpinBox(groupBoxSettings);
    spinBoxObstacleLaserScanner->setObjectName(QString::fromUtf8("spinBoxObstacleLaserScanner"));
    spinBoxObstacleLaserScanner->setGeometry(QRect(190, 10, 46, 23));
    spinBoxObstacleLaserScanner->setMinimum(1);
    spinBoxObstacleLaserScanner->setMaximum(6000);
    spinBoxObstacleLaserScanner->setSingleStep(1);
    spinBoxObstacleLaserScanner->setValue(100);
    sliderObstacleLaserScanner = new QSlider(groupBoxSettings);
    sliderObstacleLaserScanner->setObjectName(QString::fromUtf8("sliderObstacleLaserScanner"));
    sliderObstacleLaserScanner->setGeometry(QRect(190, 40, 35, 74));
    sliderObstacleLaserScanner->setMinimum(1);
    sliderObstacleLaserScanner->setMaximum(6000);
    sliderObstacleLaserScanner->setSingleStep(10);
    sliderObstacleLaserScanner->setPageStep(100);
    sliderObstacleLaserScanner->setValue(100);
    sliderObstacleLaserScanner->setSliderPosition(100);
    sliderObstacleLaserScanner->setTracking(false);
    sliderObstacleLaserScanner->setOrientation(Qt::Vertical);
    sliderObstacleLaserScanner->setTickPosition(QSlider::TicksBelow);
    sliderObstacleLaserScanner->setTickInterval(500);
    label_9 = new QLabel(groupBoxSettings);
    label_9->setObjectName(QString::fromUtf8("label_9"));
    label_9->setGeometry(QRect(190, 120, 50, 41));
    label_9->setWordWrap(true);
    groupBoxMotor = new QGroupBox(Gui);
    groupBoxMotor->setObjectName(QString::fromUtf8("groupBoxMotor"));
    groupBoxMotor->setGeometry(QRect(10, 680, 621, 281));
    qwtPlotCurrent1 = new QwtPlot(groupBoxMotor);
    qwtPlotCurrent1->setObjectName(QString::fromUtf8("qwtPlotCurrent1"));
    qwtPlotCurrent1->setGeometry(QRect(30, 20, 241, 181));
    textLabel2_6 = new QLabel(groupBoxMotor);
    textLabel2_6->setObjectName(QString::fromUtf8("textLabel2_6"));
    textLabel2_6->setGeometry(QRect(340, 250, 53, 21));
    textLabel2_7 = new QLabel(groupBoxMotor);
    textLabel2_7->setObjectName(QString::fromUtf8("textLabel2_7"));
    textLabel2_7->setGeometry(QRect(340, 240, 71, 16));
    btnResetMovement1 = new QPushButton(groupBoxMotor);
    btnResetMovement1->setObjectName(QString::fromUtf8("btnResetMovement1"));
    btnResetMovement1->setGeometry(QRect(210, 243, 61, 23));
    labelDrivenDistance1 = new QLabel(groupBoxMotor);
    labelDrivenDistance1->setObjectName(QString::fromUtf8("labelDrivenDistance1"));
    labelDrivenDistance1->setGeometry(QRect(90, 253, 51, 21));
    labelDrivenDistance1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    labelDrivenDistance2 = new QLabel(groupBoxMotor);
    labelDrivenDistance2->setObjectName(QString::fromUtf8("labelDrivenDistance2"));
    labelDrivenDistance2->setGeometry(QRect(400, 250, 51, 21));
    labelDrivenDistance2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    textLabel1_2 = new QLabel(groupBoxMotor);
    textLabel1_2->setObjectName(QString::fromUtf8("textLabel1_2"));
    textLabel1_2->setGeometry(QRect(30, 240, 71, 16));
    frameDirection2 = new QFrame(groupBoxMotor);
    frameDirection2->setObjectName(QString::fromUtf8("frameDirection2"));
    frameDirection2->setGeometry(QRect(470, 200, 111, 31));
    QPalette palette2;
    QBrush brush2(QColor(255, 255, 255, 255));
    brush2.setStyle(Qt::SolidPattern);
    palette2.setBrush(QPalette::Active, QPalette::Window, brush2);
    palette2.setBrush(QPalette::Inactive, QPalette::Window, brush2);
    palette2.setBrush(QPalette::Disabled, QPalette::Window, brush2);
    frameDirection2->setPalette(palette2);
    frameDirection2->setAutoFillBackground(true);
    frameDirection2->setFrameShape(QFrame::StyledPanel);
    frameDirection2->setFrameShadow(QFrame::Raised);
    lblDirection2 = new QLabel(frameDirection2);
    lblDirection2->setObjectName(QString::fromUtf8("lblDirection2"));
    lblDirection2->setEnabled(false);
    lblDirection2->setGeometry(QRect(10, 0, 91, 31));
    QFont font;
    font.setFamily(QString::fromUtf8("Sans Serif"));
    font.setPointSize(12);
    font.setBold(true);
    font.setItalic(false);
    font.setUnderline(false);
    font.setWeight(75);
    font.setStrikeOut(false);
    lblDirection2->setFont(font);
    lblDirection2->setAlignment(Qt::AlignCenter);
    lblDirection2->setWordWrap(true);
    btnResetMovement2 = new QPushButton(groupBoxMotor);
    btnResetMovement2->setObjectName(QString::fromUtf8("btnResetMovement2"));
    btnResetMovement2->setGeometry(QRect(520, 240, 61, 23));
    frameDirection1 = new QFrame(groupBoxMotor);
    frameDirection1->setObjectName(QString::fromUtf8("frameDirection1"));
    frameDirection1->setGeometry(QRect(160, 200, 111, 31));
    QPalette palette3;
    palette3.setBrush(QPalette::Active, QPalette::Window, brush2);
    palette3.setBrush(QPalette::Inactive, QPalette::Window, brush2);
    palette3.setBrush(QPalette::Disabled, QPalette::Window, brush2);
    frameDirection1->setPalette(palette3);
    frameDirection1->setAutoFillBackground(true);
    frameDirection1->setFrameShape(QFrame::StyledPanel);
    frameDirection1->setFrameShadow(QFrame::Raised);
    lblDirection1 = new QLabel(frameDirection1);
    lblDirection1->setObjectName(QString::fromUtf8("lblDirection1"));
    lblDirection1->setEnabled(false);
    lblDirection1->setGeometry(QRect(10, 0, 91, 31));
    lblDirection1->setFont(font);
    lblDirection1->setAlignment(Qt::AlignCenter);
    lblDirection1->setWordWrap(true);
    textLabel1 = new QLabel(groupBoxMotor);
    textLabel1->setObjectName(QString::fromUtf8("textLabel1"));
    textLabel1->setGeometry(QRect(30, 253, 53, 16));
    framePower1 = new QFrame(groupBoxMotor);
    framePower1->setObjectName(QString::fromUtf8("framePower1"));
    framePower1->setGeometry(QRect(30, 200, 111, 31));
    QPalette palette4;
    palette4.setBrush(QPalette::Active, QPalette::Window, brush2);
    palette4.setBrush(QPalette::Inactive, QPalette::Window, brush2);
    palette4.setBrush(QPalette::Disabled, QPalette::Window, brush2);
    framePower1->setPalette(palette4);
    framePower1->setAutoFillBackground(true);
    framePower1->setFrameShape(QFrame::StyledPanel);
    framePower1->setFrameShadow(QFrame::Raised);
    lblPower1 = new QLabel(framePower1);
    lblPower1->setObjectName(QString::fromUtf8("lblPower1"));
    lblPower1->setEnabled(false);
    lblPower1->setGeometry(QRect(10, 0, 91, 31));
    lblPower1->setFont(font);
    lblPower1->setAlignment(Qt::AlignCenter);
    qwtPlotCurrent2 = new QwtPlot(groupBoxMotor);
    qwtPlotCurrent2->setObjectName(QString::fromUtf8("qwtPlotCurrent2"));
    qwtPlotCurrent2->setGeometry(QRect(340, 20, 241, 181));
    framePower2 = new QFrame(groupBoxMotor);
    framePower2->setObjectName(QString::fromUtf8("framePower2"));
    framePower2->setGeometry(QRect(340, 200, 111, 31));
    QPalette palette5;
    palette5.setBrush(QPalette::Active, QPalette::Window, brush2);
    palette5.setBrush(QPalette::Inactive, QPalette::Window, brush2);
    palette5.setBrush(QPalette::Disabled, QPalette::Window, brush2);
    framePower2->setPalette(palette5);
    framePower2->setAutoFillBackground(true);
    framePower2->setFrameShape(QFrame::StyledPanel);
    framePower2->setFrameShadow(QFrame::Raised);
    lblPower2 = new QLabel(framePower2);
    lblPower2->setObjectName(QString::fromUtf8("lblPower2"));
    lblPower2->setEnabled(false);
    lblPower2->setGeometry(QRect(10, -1, 91, 31));
    lblPower2->setFont(font);
    lblPower2->setAlignment(Qt::AlignCenter);
    labelRevolutions2 = new QLabel(groupBoxMotor);
    labelRevolutions2->setObjectName(QString::fromUtf8("labelRevolutions2"));
    labelRevolutions2->setGeometry(QRect(420, 240, 31, 16));
    labelRevolutions2->setLayoutDirection(Qt::RightToLeft);
    labelRevolutions1 = new QLabel(groupBoxMotor);
    labelRevolutions1->setObjectName(QString::fromUtf8("labelRevolutions1"));
    labelRevolutions1->setGeometry(QRect(110, 240, 31, 16));
    labelRevolutions1->setLayoutDirection(Qt::RightToLeft);
    groupBoxCamera = new QGroupBox(Gui);
    groupBoxCamera->setObjectName(QString::fromUtf8("groupBoxCamera"));
    groupBoxCamera->setGeometry(QRect(650, 0, 731, 381));
    btnClearPicture = new QPushButton(groupBoxCamera);
    btnClearPicture->setObjectName(QString::fromUtf8("btnClearPicture"));
    btnClearPicture->setGeometry(QRect(620, 100, 101, 28));
    btnClearPicture->setIcon(QIcon(QString::fromUtf8(":/images/images/trashcan_empty.png")));
    btnAutoSavePicture = new QPushButton(groupBoxCamera);
    btnAutoSavePicture->setObjectName(QString::fromUtf8("btnAutoSavePicture"));
    btnAutoSavePicture->setGeometry(QRect(620, 20, 101, 28));
    btnAutoSavePicture->setIcon(QIcon(QString::fromUtf8(":/images/images/webcamreceive.png")));
    btnAutoSavePicture->setCheckable(true);
    checkBoxCamPicLive = new QCheckBox(groupBoxCamera);
    checkBoxCamPicLive->setObjectName(QString::fromUtf8("checkBoxCamPicLive"));
    checkBoxCamPicLive->setGeometry(QRect(620, 140, 71, 20));
    checkBoxCamPicLive->setChecked(true);
    btnSavePicture = new QPushButton(groupBoxCamera);
    btnSavePicture->setObjectName(QString::fromUtf8("btnSavePicture"));
    btnSavePicture->setGeometry(QRect(620, 60, 101, 28));
    btnSavePicture->setIcon(QIcon(QString::fromUtf8(":/images/images/hdd.png")));
    checkBoxAutoSave = new QCheckBox(groupBoxCamera);
    checkBoxAutoSave->setObjectName(QString::fromUtf8("checkBoxAutoSave"));
    checkBoxAutoSave->setGeometry(QRect(620, 160, 81, 20));
    groupBoxBot = new QGroupBox(Gui);
    groupBoxBot->setObjectName(QString::fromUtf8("groupBoxBot"));
    groupBoxBot->setGeometry(QRect(10, 310, 621, 361));
    labelSensorAlarm1 = new QLabel(groupBoxBot);
    labelSensorAlarm1->setObjectName(QString::fromUtf8("labelSensorAlarm1"));
    labelSensorAlarm1->setEnabled(false);
    labelSensorAlarm1->setGeometry(QRect(109, 60, 84, 20));
    labelSensorAlarm1->setFont(font);
    labelSensorAlarm1->setAlignment(Qt::AlignCenter);
    label_7 = new QLabel(groupBoxBot);
    label_7->setObjectName(QString::fromUtf8("label_7"));
    label_7->setGeometry(QRect(421, 39, 16, 16));
    labelSensorAlarm4 = new QLabel(groupBoxBot);
    labelSensorAlarm4->setObjectName(QString::fromUtf8("labelSensorAlarm4"));
    labelSensorAlarm4->setEnabled(false);
    labelSensorAlarm4->setGeometry(QRect(112, 268, 84, 21));
    labelSensorAlarm4->setFont(font);
    labelSensorAlarm4->setAlignment(Qt::AlignCenter);
    labelSensorDistance5 = new QLabel(groupBoxBot);
    labelSensorDistance5->setObjectName(QString::fromUtf8("labelSensorDistance5"));
    labelSensorDistance5->setGeometry(QRect(93, 180, 41, 16));
    labelSensorDistance5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    progressBarSensor5 = new QProgressBar(groupBoxBot);
    progressBarSensor5->setObjectName(QString::fromUtf8("progressBarSensor5"));
    progressBarSensor5->setGeometry(QRect(102, 142, 35, 18));
    progressBarSensor5->setAutoFillBackground(true);
    progressBarSensor5->setValue(-1);
    progressBarSensor5->setTextVisible(false);
    progressBarSensor5->setInvertedAppearance(true);
    progressBarSensor4 = new QProgressBar(groupBoxBot);
    progressBarSensor4->setObjectName(QString::fromUtf8("progressBarSensor4"));
    progressBarSensor4->setGeometry(QRect(161, 250, 35, 18));
    progressBarSensor4->setAutoFillBackground(true);
    progressBarSensor4->setValue(-1);
    progressBarSensor4->setTextVisible(false);
    progressBarSensor4->setInvertedAppearance(true);
    labelSensorDistance16 = new QLabel(groupBoxBot);
    labelSensorDistance16->setObjectName(QString::fromUtf8("labelSensorDistance16"));
    labelSensorDistance16->setGeometry(QRect(342, 39, 41, 16));
    labelSensorAlarm2 = new QLabel(groupBoxBot);
    labelSensorAlarm2->setObjectName(QString::fromUtf8("labelSensorAlarm2"));
    labelSensorAlarm2->setEnabled(false);
    labelSensorAlarm2->setGeometry(QRect(392, 60, 84, 20));
    labelSensorAlarm2->setFont(font);
    labelSensorAlarm2->setAlignment(Qt::AlignCenter);
    labelSensorAlarm16 = new QLabel(groupBoxBot);
    labelSensorAlarm16->setObjectName(QString::fromUtf8("labelSensorAlarm16"));
    labelSensorAlarm16->setEnabled(false);
    labelSensorAlarm16->setGeometry(QRect(341, 20, 94, 20));
    labelSensorAlarm16->setFont(font);
    labelSensorAlarm16->setAlignment(Qt::AlignCenter);
    labelSensorAlarm8 = new QLabel(groupBoxBot);
    labelSensorAlarm8->setObjectName(QString::fromUtf8("labelSensorAlarm8"));
    labelSensorAlarm8->setEnabled(false);
    labelSensorAlarm8->setGeometry(QRect(290, 300, 84, 20));
    labelSensorAlarm8->setFont(font);
    labelSensorAlarm8->setAlignment(Qt::AlignCenter);
    labelSensorAlarm5 = new QLabel(groupBoxBot);
    labelSensorAlarm5->setObjectName(QString::fromUtf8("labelSensorAlarm5"));
    labelSensorAlarm5->setEnabled(false);
    labelSensorAlarm5->setGeometry(QRect(51, 160, 84, 20));
    labelSensorAlarm5->setFont(font);
    labelSensorAlarm5->setAlignment(Qt::AlignCenter);
    labelSensorAlarm7 = new QLabel(groupBoxBot);
    labelSensorAlarm7->setObjectName(QString::fromUtf8("labelSensorAlarm7"));
    labelSensorAlarm7->setEnabled(false);
    labelSensorAlarm7->setGeometry(QRect(421, 160, 84, 20));
    labelSensorAlarm7->setFont(font);
    labelSensorAlarm7->setAlignment(Qt::AlignCenter);
    labelSensorDistance4 = new QLabel(groupBoxBot);
    labelSensorDistance4->setObjectName(QString::fromUtf8("labelSensorDistance4"));
    labelSensorDistance4->setGeometry(QRect(154, 289, 41, 16));
    labelSensorDistance4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    progressBarSensor7 = new QProgressBar(groupBoxBot);
    progressBarSensor7->setObjectName(QString::fromUtf8("progressBarSensor7"));
    progressBarSensor7->setGeometry(QRect(420, 142, 35, 18));
    progressBarSensor7->setAutoFillBackground(true);
    progressBarSensor7->setValue(-1);
    progressBarSensor7->setTextVisible(false);
    lblRobotPic = new QLabel(groupBoxBot);
    lblRobotPic->setObjectName(QString::fromUtf8("lblRobotPic"));
    lblRobotPic->setGeometry(QRect(140, 40, 281, 261));
    lblRobotPic->setPixmap(QPixmap(QString::fromUtf8(":/images/images/imgp4355_Bot-freigestellt-275x264.png")));
    lblRobotPic->setScaledContents(true);
    lblRobotPic->setAlignment(Qt::AlignCenter);
    labelSensorDistance2 = new QLabel(groupBoxBot);
    labelSensorDistance2->setObjectName(QString::fromUtf8("labelSensorDistance2"));
    labelSensorDistance2->setGeometry(QRect(394, 80, 41, 16));
    labelSensorDistance8 = new QLabel(groupBoxBot);
    labelSensorDistance8->setObjectName(QString::fromUtf8("labelSensorDistance8"));
    labelSensorDistance8->setGeometry(QRect(326, 320, 41, 16));
    labelSensorDistance8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    progressBarSensor6 = new QProgressBar(groupBoxBot);
    progressBarSensor6->setObjectName(QString::fromUtf8("progressBarSensor6"));
    progressBarSensor6->setGeometry(QRect(240, 20, 18, 35));
    progressBarSensor6->setAutoFillBackground(true);
    progressBarSensor6->setValue(-1);
    progressBarSensor6->setTextVisible(false);
    progressBarSensor6->setOrientation(Qt::Vertical);
    progressBarSensor3 = new QProgressBar(groupBoxBot);
    progressBarSensor3->setObjectName(QString::fromUtf8("progressBarSensor3"));
    progressBarSensor3->setGeometry(QRect(391, 250, 35, 18));
    progressBarSensor3->setAutoFillBackground(true);
    progressBarSensor3->setValue(-1);
    progressBarSensor3->setTextVisible(false);
    label_6 = new QLabel(groupBoxBot);
    label_6->setObjectName(QString::fromUtf8("label_6"));
    label_6->setGeometry(QRect(156, 40, 16, 16));
    labelSensorAlarm3 = new QLabel(groupBoxBot);
    labelSensorAlarm3->setObjectName(QString::fromUtf8("labelSensorAlarm3"));
    labelSensorAlarm3->setEnabled(false);
    labelSensorAlarm3->setGeometry(QRect(391, 268, 81, 21));
    labelSensorAlarm3->setFont(font);
    labelSensorAlarm3->setAlignment(Qt::AlignCenter);
    labelSensorDistance3 = new QLabel(groupBoxBot);
    labelSensorDistance3->setObjectName(QString::fromUtf8("labelSensorDistance3"));
    labelSensorDistance3->setGeometry(QRect(391, 285, 41, 16));
    labelSensorDistance6 = new QLabel(groupBoxBot);
    labelSensorDistance6->setObjectName(QString::fromUtf8("labelSensorDistance6"));
    labelSensorDistance6->setGeometry(QRect(196, 40, 41, 16));
    labelSensorDistance6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    labelSensorDistance7 = new QLabel(groupBoxBot);
    labelSensorDistance7->setObjectName(QString::fromUtf8("labelSensorDistance7"));
    labelSensorDistance7->setGeometry(QRect(424, 180, 41, 16));
    progressBarSensor2 = new QProgressBar(groupBoxBot);
    progressBarSensor2->setObjectName(QString::fromUtf8("progressBarSensor2"));
    progressBarSensor2->setGeometry(QRect(371, 60, 18, 35));
    progressBarSensor2->setAutoFillBackground(true);
    progressBarSensor2->setValue(-1);
    progressBarSensor2->setTextVisible(false);
    progressBarSensor2->setOrientation(Qt::Vertical);
    progressBarSensor8 = new QProgressBar(groupBoxBot);
    progressBarSensor8->setObjectName(QString::fromUtf8("progressBarSensor8"));
    progressBarSensor8->setGeometry(QRect(270, 300, 18, 35));
    progressBarSensor8->setAutoFillBackground(true);
    progressBarSensor8->setValue(-1);
    progressBarSensor8->setTextVisible(false);
    progressBarSensor8->setOrientation(Qt::Vertical);
    progressBarSensor8->setInvertedAppearance(true);
    labelSensorAlarm6 = new QLabel(groupBoxBot);
    labelSensorAlarm6->setObjectName(QString::fromUtf8("labelSensorAlarm6"));
    labelSensorAlarm6->setEnabled(false);
    labelSensorAlarm6->setGeometry(QRect(153, 20, 84, 20));
    labelSensorAlarm6->setFont(font);
    labelSensorAlarm6->setAlignment(Qt::AlignCenter);
    progressBarSensor16 = new QProgressBar(groupBoxBot);
    progressBarSensor16->setObjectName(QString::fromUtf8("progressBarSensor16"));
    progressBarSensor16->setGeometry(QRect(321, 20, 18, 35));
    progressBarSensor16->setAutoFillBackground(true);
    progressBarSensor16->setTextVisible(false);
    progressBarSensor16->setOrientation(Qt::Vertical);
    progressBarSensor1 = new QProgressBar(groupBoxBot);
    progressBarSensor1->setObjectName(QString::fromUtf8("progressBarSensor1"));
    progressBarSensor1->setGeometry(QRect(195, 60, 18, 35));
    progressBarSensor1->setAutoFillBackground(true);
    progressBarSensor1->setValue(-1);
    progressBarSensor1->setTextVisible(false);
    progressBarSensor1->setOrientation(Qt::Vertical);
    labelSensorDistance1 = new QLabel(groupBoxBot);
    labelSensorDistance1->setObjectName(QString::fromUtf8("labelSensorDistance1"));
    labelSensorDistance1->setGeometry(QRect(151, 80, 41, 16));
    labelSensorDistance1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
    btnSimulate = new QPushButton(Gui);
    btnSimulate->setObjectName(QString::fromUtf8("btnSimulate"));
    btnSimulate->setGeometry(QRect(1280, 790, 101, 28));
    btnSimulate->setAutoFillBackground(true);
    btnSimulate->setIcon(QIcon(QString::fromUtf8(":/images/images/kmplot.png")));
    btnSimulate->setCheckable(true);
    QWidget::setTabOrder(btnClearLog, btnTest);

    retranslateUi(Gui);

    QMetaObject::connectSlotsByName(Gui);
    } // setupUi

    void retranslateUi(QWidget *Gui)
    {
    Gui->setWindowTitle(QApplication::translate("Gui", "mrs", 0, QApplication::UnicodeUTF8));
    btnExit->setText(QApplication::translate("Gui", " E&xit", 0, QApplication::UnicodeUTF8));
    btnExit->setShortcut(QApplication::translate("Gui", "Alt+X", 0, QApplication::UnicodeUTF8));
    btnReset->setText(QApplication::translate("Gui", " &Reset", 0, QApplication::UnicodeUTF8));
    btnReset->setShortcut(QApplication::translate("Gui", "Alt+R", 0, QApplication::UnicodeUTF8));
    groupBoxNetwork->setTitle(QApplication::translate("Gui", "Network", 0, QApplication::UnicodeUTF8));
    textEditNetworkLog->setHtml(QApplication::translate("Gui", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", 0, QApplication::UnicodeUTF8));
    btnSaveNetworkLog->setText(QApplication::translate("Gui", "Save", 0, QApplication::UnicodeUTF8));
    btnClearNetworkLog->setText(QApplication::translate("Gui", " C&lear", 0, QApplication::UnicodeUTF8));
    btnClearNetworkLog->setShortcut(QApplication::translate("Gui", "Alt+L", 0, QApplication::UnicodeUTF8));
    groupBoxLog->setTitle(QApplication::translate("Gui", "Log", 0, QApplication::UnicodeUTF8));
    btnClearLog->setText(QApplication::translate("Gui", " C&lear", 0, QApplication::UnicodeUTF8));
    btnClearLog->setShortcut(QApplication::translate("Gui", "Alt+L", 0, QApplication::UnicodeUTF8));
    btnSaveLog->setText(QApplication::translate("Gui", "Save", 0, QApplication::UnicodeUTF8));
    btnTest->setText(QApplication::translate("Gui", " &Test", 0, QApplication::UnicodeUTF8));
    btnTest->setShortcut(QApplication::translate("Gui", "Alt+T", 0, QApplication::UnicodeUTF8));
    btnEnableRemote->setText(QApplication::translate("Gui", " Re&mote", 0, QApplication::UnicodeUTF8));
    btnEnableRemote->setShortcut(QApplication::translate("Gui", "Alt+M", 0, QApplication::UnicodeUTF8));
    btnDrive->setText(QApplication::translate("Gui", " &Drive", 0, QApplication::UnicodeUTF8));
    btnDrive->setShortcut(QApplication::translate("Gui", "Alt+D", 0, QApplication::UnicodeUTF8));
    groupBoxLaserScanner->setTitle(QApplication::translate("Gui", "Laser Scanner", 0, QApplication::UnicodeUTF8));
    checkBoxAngleView->setText(QApplication::translate("Gui", "180\302\260", 0, QApplication::UnicodeUTF8));
    checkBoxHiResView->setText(QApplication::translate("Gui", "HiRes", 0, QApplication::UnicodeUTF8));
    labelLaserTop->setText(QApplication::translate("Gui", "1:1", 0, QApplication::UnicodeUTF8));
    label_10->setText(QApplication::translate("Gui", "1:1", 0, QApplication::UnicodeUTF8));
    label_11->setText(QApplication::translate("Gui", "1:10", 0, QApplication::UnicodeUTF8));
    checkBoxLaserAlert->setText(QApplication::translate("Gui", "Alert", 0, QApplication::UnicodeUTF8));
    checkBoxAntiAlias->setToolTip(QApplication::translate("Gui", "AntiAlias", 0, QApplication::UnicodeUTF8));
    checkBoxAntiAlias->setText(QApplication::translate("Gui", "AA", 0, QApplication::UnicodeUTF8));
    label->setText(QApplication::translate("Gui", "Obstacle alarm", 0, QApplication::UnicodeUTF8));
    checkBoxSaveSettings->setText(QApplication::translate("Gui", "Save settings on exit", 0, QApplication::UnicodeUTF8));
    label_5->setText(QApplication::translate("Gui", "Motor2 speed", 0, QApplication::UnicodeUTF8));
    label_4->setText(QApplication::translate("Gui", "Robot Slot (angle)", 0, QApplication::UnicodeUTF8));
    label_3->setText(QApplication::translate("Gui", "Servo 1", 0, QApplication::UnicodeUTF8));
    label_2->setText(QApplication::translate("Gui", "Motor1 speed", 0, QApplication::UnicodeUTF8));
    label_9->setText(QApplication::translate("Gui", "Obstacle Laser Scanner", 0, QApplication::UnicodeUTF8));
    groupBoxMotor->setTitle(QApplication::translate("Gui", "Motors", 0, QApplication::UnicodeUTF8));
    textLabel2_6->setText(QApplication::translate("Gui", "Distance:", 0, QApplication::UnicodeUTF8));
    textLabel2_7->setText(QApplication::translate("Gui", "Revolutions:", 0, QApplication::UnicodeUTF8));
    btnResetMovement1->setText(QApplication::translate("Gui", "Reset", 0, QApplication::UnicodeUTF8));
    labelDrivenDistance1->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelDrivenDistance2->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    textLabel1_2->setText(QApplication::translate("Gui", "Revolutions:", 0, QApplication::UnicodeUTF8));
    lblDirection2->setText(QApplication::translate("Gui", "FORWARD", 0, QApplication::UnicodeUTF8));
    btnResetMovement2->setText(QApplication::translate("Gui", "Reset", 0, QApplication::UnicodeUTF8));
    lblDirection1->setText(QApplication::translate("Gui", "FORWARD", 0, QApplication::UnicodeUTF8));
    textLabel1->setText(QApplication::translate("Gui", "Distance:", 0, QApplication::UnicodeUTF8));
    lblPower1->setText(QApplication::translate("Gui", "MOTOR 1", 0, QApplication::UnicodeUTF8));
    lblPower2->setText(QApplication::translate("Gui", "MOTOR 2", 0, QApplication::UnicodeUTF8));
    labelRevolutions2->setText(QApplication::translate("Gui", "0", 0, QApplication::UnicodeUTF8));
    labelRevolutions1->setText(QApplication::translate("Gui", "0", 0, QApplication::UnicodeUTF8));
    groupBoxCamera->setTitle(QApplication::translate("Gui", "Camera", 0, QApplication::UnicodeUTF8));
    btnClearPicture->setText(QApplication::translate("Gui", "Clear", 0, QApplication::UnicodeUTF8));
    btnAutoSavePicture->setText(QApplication::translate("Gui", "&Start", 0, QApplication::UnicodeUTF8));
    btnAutoSavePicture->setShortcut(QApplication::translate("Gui", "Alt+S", 0, QApplication::UnicodeUTF8));
    checkBoxCamPicLive->setText(QApplication::translate("Gui", "Live", 0, QApplication::UnicodeUTF8));
    btnSavePicture->setText(QApplication::translate("Gui", "Save", 0, QApplication::UnicodeUTF8));
    checkBoxAutoSave->setText(QApplication::translate("Gui", "Auto Save", 0, QApplication::UnicodeUTF8));
    groupBoxBot->setTitle(QApplication::translate("Gui", "Bot", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm1->setText(QApplication::translate("Gui", "SENSOR 1", 0, QApplication::UnicodeUTF8));
    label_7->setText(QApplication::translate("Gui", "US", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm4->setText(QApplication::translate("Gui", "SENSOR 4", 0, QApplication::UnicodeUTF8));
    labelSensorDistance5->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelSensorDistance16->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm2->setText(QApplication::translate("Gui", "SENSOR 2", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm16->setText(QApplication::translate("Gui", "SENSOR 16", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm8->setText(QApplication::translate("Gui", "SENSOR 8", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm5->setText(QApplication::translate("Gui", "SENSOR 5", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm7->setText(QApplication::translate("Gui", "SENSOR 7", 0, QApplication::UnicodeUTF8));
    labelSensorDistance4->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    lblRobotPic->setText(QString());
    labelSensorDistance2->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelSensorDistance8->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    label_6->setText(QApplication::translate("Gui", "IR", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm3->setText(QApplication::translate("Gui", "SENSOR 3", 0, QApplication::UnicodeUTF8));
    labelSensorDistance3->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelSensorDistance6->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelSensorDistance7->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    labelSensorAlarm6->setText(QApplication::translate("Gui", "SENSOR 6", 0, QApplication::UnicodeUTF8));
    labelSensorDistance1->setText(QApplication::translate("Gui", "0 cm", 0, QApplication::UnicodeUTF8));
    btnSimulate->setText(QApplication::translate("Gui", " S&imulate", 0, QApplication::UnicodeUTF8));
    btnSimulate->setShortcut(QApplication::translate("Gui", "Alt+I", 0, QApplication::UnicodeUTF8));
    Q_UNUSED(Gui);
    } // retranslateUi

};

namespace Ui {
    class Gui: public Ui_Gui {};
} // namespace Ui

#endif // UI_GUI_H
